DROP SCHEMA IF EXISTS spices CASCADE;
CREATE SCHEMA spices;

SET search_path = spices;

CREATE TABLE Spices(
  name varchar(50),
  descr text,
  price decimal(13,2),
  size varchar(10),
  id serial PRIMARY KEY,
  food varchar(255),
  category varchar(100));
  
CREATE TABLE Users(
  email varchar(50),
  name varchar(50),
  user_Id serial PRIMARY KEY);
  
CREATE TABLE Category(
  catagory varchar(50) PRIMARY KEY
  );
  
CREATE TABLE Spice_Category(
  id int NOT NULL REFERENCES Spices,
  category varchar(50) NOT NULL REFERENCES Category,
  PRIMARY KEY (id, category));

-- 1-20
 
-- 21-40
INSERT INTO Spices VALUES('Epazote','Epazote is common to Mexican cooking. While fresh epazote should be your first choice, it is often difficult to find. When substituting our dried herb, use one-half the amount specified for fresh leaves. Epazote is most commonly found in bean dishes. It is also used in soups and moles.  Epazote has a slightly tangy flavor, reminiscent of oregano. It is used both for flavor and for its ability to reduce the flatulence associated with bean dishes.',12.99,4,21,'Bean dishes, soups, mole','Mexican');
INSERT INTO Spices VALUES('Mexican Oregano','This type of oregano, grown in Mexico or California, has a very different flavor than the Mediterranean oregano - stronger and more bitter. More robust than Greek, this oregano stands up to the stronger flavors used in Mexican cooking such as hot chili peppers and cumin, which could overwhelm the more delicate oregano from the Mediterranean.',6.99,4,22,'artichokes, beans, chicken, eggplant, fish, lamb, mushrooms, pasta, peppers, pizza, pork, potatoes, rabbit, sausages, tomatoes, veal, zucchini','Mexican');
INSERT INTO Spices VALUES('Mexican Vanilla Beans','Mexico has always had the reputation for the best vanilla, but it is much more difficult and expensive to produce the highest quality vanilla crops. Vanilla is native to the Latin American isthmus, where it has been cultivated and used as both flavoring and currency for centuries. Although vanilla beans are grown in several locations today, until the 1800’s Mexico maintained a monopoly on vanilla beans in spite of the fact that explorers constantly uprooted the orchid vines to replant in their native lands. Botanists finally came to realize that the melipone bees, native only to Mexico, were pollinating the flowers. Eventually, a man on the island of Reunion discovered that the pointed stick of a bamboo shoot could be used to hand-pollinate the flowers. Once this was discovered, the French planted vanilla on many of the tropical islands they ruled. To this day, former French colonies within about 25 degrees of the equator (which enjoy warm, tropical climates) produce about 80% of the world’s vanilla.',4.49,3,23,'apples, apricots, chocolate, custards, fish, fruit, ice cream, plums, shellfish','Mexican');
INSERT INTO Spices VALUES('Whole Spanish Anise Seed','Anise seed is native to the Mediterranean basin, and has been used throughout history in both sweet and savory applications. Anise has long been known as an aid to digestion. The Romans ended their elaborate feasts with anise cakes. In the Mediterranean, anise is featured heavily in cakes, breads, cookies and liquors. In small amounts, anise makes a nice addition to sausage, or in tomato sauce.',7.99,8,24,'sausage, chutney, brisket, bread, cake','German, Italian, Spanish');
INSERT INTO Spices VALUES('California Sweet Basil','Basil has now become the most popular herb used in this country. Basil, garlic and tomatoes form an unbeatable trio.  Until recently, French basil had a reputation for supremacy. Now, domestic basil is generally regarded as superior to imported basil, in part because the drying process in California has advanced to a very high level. The fresh, sweet basil flavor and nice green color is maintained beautifully. Stored properly, the flavor of these large leaf flakes can stay strong and fresh for months.',7.99,4,25,'cheese, chicken, duck, eggplant, eggs, fish, lamb, liver, olive oil, onions, pasta, pesto, pizza, pork, potatoes, rabbit, salads, shellfish, soups, sweet peppers, tomatoes, veal, vegetables, vinegars, zucchini, tomato sauce','Italian');
INSERT INTO Spices VALUES('Whole Fennel Seeds','Fennel Seed has a delicate flavor; light and sweet, similar to anise. Use of fennel has a long history, dating back to the Chinese and Hindus who used it as a cure for snake bites. Fennel was hung over doors in the Middle Ages to ward off evil spirits.',5.29,8,26,'Cheese, sausage, fish, sauces','Greek and Turkish, Indian, Italian');
INSERT INTO Spices VALUES('Granulated Garlic Powder','Regular granulated garlic is the standard for use in most recipes. It takes about 20 minutes for full flavor release, but is fine enough to taste garlicky in a much shorter time. These garlic products are pure dehydrated garlic: no preservatives, no anti-caking agents.',5.29,8,27,'beans, beef, beets, cabbage, chicken, eggplant, fish, lamb, lentils, mushrooms, pasta, pork, potatoes, rice, shellfish, spinach, tomatoes, zucchini','Cajun, Caribbean, Eastern European, Garlic, Greek and Turkish, Italian');
INSERT INTO Spices VALUES('Italian Herb Blend','One whiff of this blend will bring to mind everything you recall about dining in your favorite Italian restaurant -- and the scent gets much better when you cook with it!  Use 1 teaspoon per cup of tomato sauce to make flavorful sauce for spaghetti, pizza, veal parmesan, or pasta noodles. To improve the taste of a store-bought pizza, crush herbs between your palms and sprinkle over the top before baking. Use it to roast Italian-style chicken or fish.  Hand mixed from: oregano, basil, marjoram, thyme, and crushed rosemary.',6.99,4,28,'sauces, pizza, chicken, fish','Italian');
INSERT INTO Spices VALUES('Tomato Powder','Tomato powder has a flavor so rich and tomato-ey you will not believe it, until you taste it. It is the sweetest red tomatoes of the crop, spray-dried into a fine powder.',8.99,7,29,'sauces, pasta, bread, stews, gumbo, chili','Italian');
INSERT INTO Spices VALUES('Turkish Bay Leaves','The flavor of these Turkish bay leaves is far milder and more complex than that of domestic bay; it adds a subtly sweet astringency to dishes. Only one or two are needed to enhance a whole roast, pot of soup or stew.',7.99,4,30,'beans, game, lentils, potatoes, risotto, shellfish, soups, stews, tomatoes','Cajun, Eastern European, English, Greek and Turkish, Hungarian, Irish');
INSERT INTO Spices VALUES('Organic Powdered Sassafras Leaves','Gumbo file powder is a necessity for cooking authentic Creole or Cajun cuisine. Quite simply, gumbo file powder is the powdered leaves of the sassafras tree. When ground, they have a rich, cooling smell, reminiscent of eucalyptus crossed with juicy fruit gum.',7.99,4,31,'gumbo, soups, stews','Cajun');
INSERT INTO Spices VALUES('Cajun Seasoning','Cajun Seasonings are useful, whether you are a Cajun cook or not. This is the flavor you get when you taste a blackened dish; just be aware that the actual blackening comes from a very hot fire. This can be from a very hot gas grill, or in a professional kitchen - if you try to blacken in a home kitchen you are likely to set off the fire alarm. We really like this seasoning without being blackened as it iss just a darned tasty, all-purpose seasoning.',4.69,4,32,'fish, chicken, steak, pork, ribs, eggs, potatoes','Cajun');
INSERT INTO Spices VALUES('Parsley Flakes','Parsley flakes make a colorful garnish.  The rich forest green color of this herb, along with its sweet flavor, makes it the ideal herb for both flavor and garnish.  Parsley is very lightweight--one ounce will give you almost two cups of parsley.',6.99,4,33,'chicken, eggplant, eggs, fish, game, lentils, mushrooms, mussels, pasta, peas, potatoes, poultry, rice, seafood, tomatoes, zucchini, lemon','Cajun, Eastern European, Greek and Turkish');
INSERT INTO Spices VALUES('Scallions','Scallions, from a non-bulb-forming onion, are similar in their delicate, mild flavor to young green onions. Add them to soups, sauces, salads, eggs, or vegetable medleys, or as an attractive garnish on nearly any savory dish.  These fancy freeze-dried scallions retain nearly all the flavor and color of fresh scallions, with a much longer shelf life. Keep them around to throw together beautiful dishes quickly.  Freeze-dried scallions are extremely lightweight - 1/4 ounce is about 1 cup of scallions.',4.59,1,34,'soups, sauces, salads, eggs','Cajun');
INSERT INTO Spices VALUES('Whole Allspice Berries','Our premium berries from Jamaica have a sweet flavor reminiscent of cloves, cinnamon and a hint of nutmeg. Even though its name suggests a mixture of spices, allspice is a single berry from the Jamaican bayberry tree. Its complex sweetness lends allspice a great deal of versatility. Whole, it is used in poached fish stock, vegetable and fruit pickles, and for wild game. Ground, it is found in spice cakes, puddings, cookies, gravies, bbq sauce and is a key ingredient in Caribbean jerk dishes. It is often used in German sausages and is so common in English baking that it is sometimes known as English Spice.',5.59,4,35,'beef, beets, cabbage, carrots, corned beef, fruit pies, game, grains, lamb, meats, onions, pumpkin, rabbit, soups, spinach, squash, stews, sweet potatoes, tomatoes, turnips','Caribbean, Eastern European');
INSERT INTO Spices VALUES('Arrowroot Powder','Arrowroot is a wonderful, clear thickener used in gravies, sauces and pie fillings. It is also more easily digested than other thickening agents. While true arrowroot comes from the marantha plant of St. Vincent, this is currently unavailable. Our arrowroot comes from the more common cassava, from Brazil. It contains high amounts of amyl pectin, a starchy thickener',6.29,8,36,'gravy, stews, sauces','Caribbean, Irish');
INSERT INTO Spices VALUES('Powdered Ginger','Dehydrated Ginger root comes in whole and powdered form. It is very healthy and useful for baking, marinades and sauces. Once you find ginger creeping into your cooking, you will be surprised at the subtle way it has of incorporating itself into more and more of your culinary repertoire.',5.59,4,37,'carrots, chicken, chocolate, fruit, ham, ice cream, melon, onions, pork, pumpkin, rice, tomatoes.','Caribbean, Chinese and Far Eastern, German, Scandinavian, Thai');
INSERT INTO Spices VALUES('Ground Mace','Mace is the outer shell of the nutmeg fruit. It has a lighter, sweeter flavor.',4.29,1,38,'meatballs, doughnuts, stews, sauces, stuffing','Caribbean, Eastern European, German');
INSERT INTO Spices VALUES('Ground Nutmeg','Nutmeg has a flavor that is quite strong. In small amounts, it blends in with great subtlety. You will find it called for in many vegetable recipes such as squash, spinach, and sweet potato pie, as well as in meatballs and sausages. French white sauces often call for a pinch.',12.99,4,39,'broccoli, cabbage, carrots, cauliflower, cheese, custards, eggs, fruits, lamb, pasta, potatoes, pumpkin, raisins, ricotta cheese, rice, sausages, spinach, squash, stuffing, veal','Caribbean, Eastern European, English');
INSERT INTO Spices VALUES('Hibiscus Blossoms','Also known as flor de Jamaica, roselle or carcade, hibiscus has a tart, pomegranate-like flavor, and is usually steeped in hot water like tea. Hibiscus is native to West Africa, where it is used to make bissap, the national drink of Senegal. It is the main ingredient in the popular Mexican drink “Agua de Jamaica.” It is wonderful in savory sauces and marinades. Hibiscus also makes a great base for a sweetened reduction sauce, and is used in jams and preserves. Hibiscus syrup or frosting is naturally pink and delicious on baked goods. Brewers love hibiscus for its sweet-tart flavor and bright color.',6.99,4,40,'sauces, marinades, jams, syrup, Aqua de Jamaica','Caribbean, Mexican');
-- 41-60

-- 61-80

-- 81-100

